################# BEGINNING RUN: TIME: 2024-02-26 03:13:35.987216 #################
stdout: 
sterr: Traceback (most recent call last):
  File "/home/ubuntu/InferenceTest1/rec/inference/pipeline/inference.py", line 26, in <module>
    print(f' connected to pinecone {PINECONE_CLIENT.list_indices()}')
AttributeError: 'Pinecone' object has no attribute 'list_indices'. Did you mean: 'list_indexes'?

